//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR.MVCWebSite.FacultiesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacultyDTO", Namespace="http://schemas.datacontract.org/2004/07/SR.ApplicationServices.DTOs")]
    [System.SerializableAttribute()]
    public partial class FacultyDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacultiesService.IFaculties")]
    public interface IFaculties {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaculties/GetFaculties", ReplyAction="http://tempuri.org/IFaculties/GetFacultiesResponse")]
        SR.MVCWebSite.FacultiesService.FacultyDTO[] GetFaculties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaculties/GetFaculties", ReplyAction="http://tempuri.org/IFaculties/GetFacultiesResponse")]
        System.Threading.Tasks.Task<SR.MVCWebSite.FacultiesService.FacultyDTO[]> GetFacultiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaculties/PostFaculty", ReplyAction="http://tempuri.org/IFaculties/PostFacultyResponse")]
        string PostFaculty(SR.MVCWebSite.FacultiesService.FacultyDTO facDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaculties/PostFaculty", ReplyAction="http://tempuri.org/IFaculties/PostFacultyResponse")]
        System.Threading.Tasks.Task<string> PostFacultyAsync(SR.MVCWebSite.FacultiesService.FacultyDTO facDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaculties/PutFaculty", ReplyAction="http://tempuri.org/IFaculties/PutFacultyResponse")]
        string PutFaculty(SR.MVCWebSite.FacultiesService.FacultyDTO facDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaculties/PutFaculty", ReplyAction="http://tempuri.org/IFaculties/PutFacultyResponse")]
        System.Threading.Tasks.Task<string> PutFacultyAsync(SR.MVCWebSite.FacultiesService.FacultyDTO facDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaculties/DeleteFaculty", ReplyAction="http://tempuri.org/IFaculties/DeleteFacultyResponse")]
        string DeleteFaculty(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaculties/DeleteFaculty", ReplyAction="http://tempuri.org/IFaculties/DeleteFacultyResponse")]
        System.Threading.Tasks.Task<string> DeleteFacultyAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacultiesChannel : SR.MVCWebSite.FacultiesService.IFaculties, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacultiesClient : System.ServiceModel.ClientBase<SR.MVCWebSite.FacultiesService.IFaculties>, SR.MVCWebSite.FacultiesService.IFaculties {
        
        public FacultiesClient() {
        }
        
        public FacultiesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacultiesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacultiesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacultiesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SR.MVCWebSite.FacultiesService.FacultyDTO[] GetFaculties() {
            return base.Channel.GetFaculties();
        }
        
        public System.Threading.Tasks.Task<SR.MVCWebSite.FacultiesService.FacultyDTO[]> GetFacultiesAsync() {
            return base.Channel.GetFacultiesAsync();
        }
        
        public string PostFaculty(SR.MVCWebSite.FacultiesService.FacultyDTO facDTO) {
            return base.Channel.PostFaculty(facDTO);
        }
        
        public System.Threading.Tasks.Task<string> PostFacultyAsync(SR.MVCWebSite.FacultiesService.FacultyDTO facDTO) {
            return base.Channel.PostFacultyAsync(facDTO);
        }
        
        public string PutFaculty(SR.MVCWebSite.FacultiesService.FacultyDTO facDTO) {
            return base.Channel.PutFaculty(facDTO);
        }
        
        public System.Threading.Tasks.Task<string> PutFacultyAsync(SR.MVCWebSite.FacultiesService.FacultyDTO facDTO) {
            return base.Channel.PutFacultyAsync(facDTO);
        }
        
        public string DeleteFaculty(int id) {
            return base.Channel.DeleteFaculty(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteFacultyAsync(int id) {
            return base.Channel.DeleteFacultyAsync(id);
        }
    }
}
