//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR.MVCWebSite.NationalitiesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NationalityDTO", Namespace="http://schemas.datacontract.org/2004/07/SR.ApplicationServices.DTOs")]
    [System.SerializableAttribute()]
    public partial class NationalityDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NationalitiesService.INationalities")]
    public interface INationalities {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalities/GetNationalities", ReplyAction="http://tempuri.org/INationalities/GetNationalitiesResponse")]
        SR.MVCWebSite.NationalitiesService.NationalityDTO[] GetNationalities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalities/GetNationalities", ReplyAction="http://tempuri.org/INationalities/GetNationalitiesResponse")]
        System.Threading.Tasks.Task<SR.MVCWebSite.NationalitiesService.NationalityDTO[]> GetNationalitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalities/PostNationality", ReplyAction="http://tempuri.org/INationalities/PostNationalityResponse")]
        string PostNationality(SR.MVCWebSite.NationalitiesService.NationalityDTO natDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalities/PostNationality", ReplyAction="http://tempuri.org/INationalities/PostNationalityResponse")]
        System.Threading.Tasks.Task<string> PostNationalityAsync(SR.MVCWebSite.NationalitiesService.NationalityDTO natDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalities/PutNationality", ReplyAction="http://tempuri.org/INationalities/PutNationalityResponse")]
        string PutNationality(SR.MVCWebSite.NationalitiesService.NationalityDTO natDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalities/PutNationality", ReplyAction="http://tempuri.org/INationalities/PutNationalityResponse")]
        System.Threading.Tasks.Task<string> PutNationalityAsync(SR.MVCWebSite.NationalitiesService.NationalityDTO natDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalities/DeleteNationality", ReplyAction="http://tempuri.org/INationalities/DeleteNationalityResponse")]
        string DeleteNationality(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalities/DeleteNationality", ReplyAction="http://tempuri.org/INationalities/DeleteNationalityResponse")]
        System.Threading.Tasks.Task<string> DeleteNationalityAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INationalitiesChannel : SR.MVCWebSite.NationalitiesService.INationalities, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NationalitiesClient : System.ServiceModel.ClientBase<SR.MVCWebSite.NationalitiesService.INationalities>, SR.MVCWebSite.NationalitiesService.INationalities {
        
        public NationalitiesClient() {
        }
        
        public NationalitiesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NationalitiesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalitiesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalitiesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SR.MVCWebSite.NationalitiesService.NationalityDTO[] GetNationalities() {
            return base.Channel.GetNationalities();
        }
        
        public System.Threading.Tasks.Task<SR.MVCWebSite.NationalitiesService.NationalityDTO[]> GetNationalitiesAsync() {
            return base.Channel.GetNationalitiesAsync();
        }
        
        public string PostNationality(SR.MVCWebSite.NationalitiesService.NationalityDTO natDTO) {
            return base.Channel.PostNationality(natDTO);
        }
        
        public System.Threading.Tasks.Task<string> PostNationalityAsync(SR.MVCWebSite.NationalitiesService.NationalityDTO natDTO) {
            return base.Channel.PostNationalityAsync(natDTO);
        }
        
        public string PutNationality(SR.MVCWebSite.NationalitiesService.NationalityDTO natDTO) {
            return base.Channel.PutNationality(natDTO);
        }
        
        public System.Threading.Tasks.Task<string> PutNationalityAsync(SR.MVCWebSite.NationalitiesService.NationalityDTO natDTO) {
            return base.Channel.PutNationalityAsync(natDTO);
        }
        
        public string DeleteNationality(int id) {
            return base.Channel.DeleteNationality(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteNationalityAsync(int id) {
            return base.Channel.DeleteNationalityAsync(id);
        }
    }
}
